version: "3"
services:
  mlflow-extend:
<<<<<<< HEAD
<<<<<<< HEAD
    volumes:
      - .:/mlflow-extend
      - ~/.ssh:/root/.ssh
=======
>>>>>>> Updates
=======
    volumes:
      - .:/mlflow-extend
      - ~/.ssh:/root/.ssh
>>>>>>> Update config
    command: /bin/sh -c "while sleep 1000; do :; done"
