name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: >
            ${{ runner.os }}-pip-
            ${{ hashFiles('**/requirements.txt') }}-
            ${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run type check
        run: mypy .

      - name: Run tests
        run: ./dev/test.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: ${{ runner.os }}-${{ matrix.python-version }}
          fail_ci_if_error: true

      - name: Verify package can be installed
        run: pip install -e .

      - name: Verify example can be executed
        run: python examples/quickstart.py

      - name: Build package
        run: python setup.py bdist_wheel

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: >
            ${{ runner.os }}-pip-
            ${{ hashFiles('**/requirements.txt') }}-
            ${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: flake8
        run: flake8 .

      - name: isort
        run: isort --check-only .

      - name: black
        run: black --check .
