name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: >
            ${{ runner.os }}-pip-
            ${{ hashFiles('**/requirements.txt') }}-
            ${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run lint
        run: ./dev/lint.sh

      - name: Run tests
        run: ./dev/test.sh

      - name: Verify package can be installed
        run: pip install -e .

      - name: Verify example can be executed
        run: python examples/quickstart.py

      - name: Build package
        run: python setup.py bdist_wheel

      - name: Build documentation
        working-directory: docs
        run: make html

      - name: Upload documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: docs/build/html
